version: '3.5'

services:

  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: unless-stopped
    env_file: ./secrets/secrets_postgres.txt
    volumes:
        - ./postgres:/data/dump
        - ./postgres/init-dump.sh:/docker-entrypoint-initdb.d/init-dump.sh
    ports:
      - "5432:5432"
    networks:
      - postgres
      
      
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file: ./secrets/secrets_pgadmin.txt
    volumes:
        - ./pgadmin/servers.json:/pgadmin4/servers.json
        - ./pgadmin/pgpass:/pgpass
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres 
    entrypoint: >
      /bin/sh -c "
      cp -f /pgpass /var/lib/pgadmin/;
      chmod 600 /var/lib/pgadmin/pgpass;
      chown pgadmin:pgadmin /var/lib/pgadmin/pgpass;
      /entrypoint.sh
      "
    
  mongo:
    container_name: mongo_container
    image: mongo:latest
    restart: unless-stopped
    env_file: ./secrets/secrets_mongo.txt
    networks:
      - postgres

  mongo-express:
    container_name: mongo-express_container
    image: mongo-express:latest
    restart: unless-stopped
    env_file: ./secrets/secrets_mongo-express.txt
    ports:
      - "${ME_CONFIG_MONGODB_PORT:-8081}:8081"
    networks:
      - postgres
      
      
  python:
    container_name: python_container
    restart: unless-stopped
    build: ./python/.
    image: pythonscript_container
    networks:
      - postgres
    

networks:
  postgres:
    driver: bridge